name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  REPO_URL: git@github.com:mathworldtesting/fastapi-postgresql.git

jobs:   
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:      
      - name: Setup python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: install dependencies
        run: |
          pip -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
            host: ${{ secrets.SSH_HOST }}  # IP address of the server you wish to ssh into
            username: ${{ secrets.SSH_USERNAME }}  # username of the server you wish to ssh into
            key: ${{ secrets.SSH_KEY }} # Private key for the server                        
            script: |
              mkdir apps
              cd apps
              git clone ${{ env.REPO_URL }}
              ls
              