
name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
      # Add your tests here. For example:  pytest

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to your app directory
          sudo mkdir -p /app
          cd app
          
          # Ensure Git is installed
          sudo apt-get update
          sudo apt-get install -y git
          
          # Clone the repository
          git clone git@github.com:mathworldtesting/fastapi-postgresql.git
          
          # Ensure Python 3.12 is installed and used
          pyenv install -s 3.12.0
          pyenv global 3.12.0
          
          # Update dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Install or upgrade Uvicorn
          pip install --upgrade uvicorn
          
          # Stop the existing Uvicorn process if it's running
          pkill -f uvicorn || true
          
          # Start Uvicorn in the background
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          
          # Optional: Add a small delay and check if Uvicorn is running
          sleep 5
          ps aux | grep uvicorn