name: Deploy FastAPI PostgreSQL to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Update package list and install Python 3.12 and venv
          sudo apt update
          sudo apt install -y python3.12 python3.12-venv

          # Ensure the app directory exists
          mkdir -p ~/app
          cd ~/app
          
          # Clone or pull the repository
          if [ -d "app" ]; then
            cd app
            git pull origin main
          else
            git clone https://github.com/mathworldtesting/fastapi-postgresql.git
            cd app
          fi
          
          # Create and activate virtual environment
          python3.12 -m venv venv
          source venv/bin/activate
          
          # Update pip and install dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Apply any database migrations (if using Alembic)
          pip install alembic
          alembic upgrade head
          
          # Restart the application (adjust as needed)
          # If using systemd:
          # sudo systemctl restart fastapi-postgresql
          
          # If using a simple background process:
          pkill -f "uvicorn main:app" || true
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &