name: Deploy FastAPI PostgreSQL to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }} # the public IP address of your DigitalOcean instance
        username: ${{ secrets.SSH_USERNAME }} # the user we created for our digitalocean instance
        key: ${{ secrets.SSH_KEY }} # the private key we created for our digitalocean instance
        script: |
          # Ensure the app directory exists
          mkdir -p ~/app
          cd ~/app
          
          # Clone or pull the repository
          if [ -d "fastapi-postgresql" ]; then
            cd fastapi-postgresql
            git pull origin main
          else
            git clone https://github.com/mathworldtesting/fastapi-postgresql.git
            cd fastapi-postgresql
          fi
          
          # Ensure Python and pip are available
          python3 -m venv venv
          source venv/bin/activate
          
          # Update dependencies
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Apply any database migrations (if using Alembic)
          alembic upgrade head
          
          # Restart the application (adjust as needed)
          # If using systemd:
          # sudo systemctl restart fastapi-postgresql
          
          # If using a simple background process:
          pkill -f "uvicorn main:app" || true
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &